name: Packer Build CI

on:
  pull_request:
    types: [closed]
    branches: ["main"]
  # push:
  #   branches: ["main"]
  #pull_request:
    #branches: ["main"]

jobs:
  build:
    name: packer-build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      ami_id: ${{ steps.packer_run.outputs.ami }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USERNAME : ${{ secrets.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}  
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}  
        ports:
          - 3306:3306
  
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Load Environment Variables
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV  
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }} " >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
 
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
        env:
          SERVER_PORT: "8800"
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: "127.0.0.1"
          PORT: "3306"

      - name: Create Zip File
        run: |
              zip -r webapp.zip .
              cp webapp.zip packer/
              ls -la packer/
        
      - name: List Files
        run: ls -al

      - name: Upload Zip File
        uses: actions/upload-artifact@v4
        with:
          name: webapp zip creation
          path: webapp.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     
      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: ${{ secrets.GCP_ACCOUNT_ID }}


      - name: Run Packer
        id: packer_run
        run: |
          # Install Packer non-interactively
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install packer -y
          
          # Navigate to packer directory and run build
          ls
          cd packer
          packer init webapp.pkr.hcl

          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "dev_user=${{ secrets.DEV_USER }}" \
            -var "demo_user=${{ secrets.DEMO_USER }}" \
            -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
            -var "db_username=${{ secrets.DB_EC2_USER }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_database=${{ secrets.DB_DATABASE }}" \
            -var "server_port=${{ secrets.SERVER_PORT }}" \
            -var "db_host=${{ secrets.DB_HOST }}" \
            -manifest-file=manifest.json \
            webapp.pkr.hcl
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "ami=$AMI_ID" >> "$GITHUB_OUTPUT"
          echo "Generated AMI ID: $AMI_ID"
      
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest 
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Debug AMI ID
        run: |
          echo "AMI ID: ${{ needs.build.outputs.ami_id }}"

      - name: Configure DEMO AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEMO_GITHUB_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEMO_GITHUB_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
        
      - name: Update Launch Template
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-data '{"ImageId":"${{ needs.build.outputs.ami_id }}"}' \
            --source-version '$Latest' \
            --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }}

      - name: Start Instance Refresh
        id: start_refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.ASG_NAME }} --query 'InstanceRefreshId' --output text)
          echo "refresh_id=$REFRESH_ID" >> $GITHUB_OUTPUT

      - name: Wait for Instance Refresh
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.ASG_NAME }} --instance-refresh-ids ${{ steps.start_refresh.outputs.refresh_id }} --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$STATUS" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              exit 0
            elif [ "$STATUS" = "Failed" ]; then
              echo "Instance refresh failed"
              exit 1
            else
              echo "Instance refresh in progress. Current status: $STATUS"
              sleep 30
            fi
          done

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true


          
      # - name: Retrieve Latest GCP Image and Save IMAGE_ID
      #   run: |
      #     GCP_IMAGE_ID=$(gcloud compute images list \
      #     --project=${{ secrets.GCP_ACCOUNT_ID }} \
      #     --sort-by="~creationTimestamp" \
      #     --limit=1 \
      #     --format="value(NAME)")

      #     if [[ -n "$GCP_IMAGE_ID" ]]; then
      #         echo "Found latest GCP Image: $GCP_IMAGE_ID"
      #         echo "GCP_IMAGE_ID=$GCP_IMAGE_ID" >> $GITHUB_ENV
      #     else
      #         echo "No GCP Image found!"
      #         exit 1
      #     fi


            

 
      # - name: Share GCP Image with Demo Project
      #   run: |
      #     if [[ -n "$GCP_IMAGE_ID" ]]; then
      #       gcloud compute images add-iam-policy-binding $GCP_IMAGE_ID \
      #         --project=${{ secrets.GCP_ACCOUNT_ID }} \
      #         --member="serviceAccount:${{ secrets.GCP_SA_DEMO }}" \
      #         --role="roles/compute.imageUser"
          
      #       echo "Image $GCP_IMAGE_ID shared with DEMO Project"
      #     else
      #       echo "No GCP Image ID found!"
      #       exit 1
      #     fi

      # - name: Copy GCP Image to Demo Project
      #   env:
      #     GCP_ACCOUNT_ID: ${{ secrets.GCP_ACCOUNT_ID }}
      #     DEMO_GCP_ACCOUNT_ID: ${{ secrets.DEMO_GCP_ACCOUNT_ID }}
      #   run: |
      #     echo "Copying image from DEV ($GCP_ACCOUNT_ID) to DEMO ($DEMO_GCP_ACCOUNT_ID)..."
      #     gcloud compute images create "webapp-$(date +%s)" \
      #       --source-image="$GCP_IMAGE_ID" \
      #       --source-image-project="$GCP_ACCOUNT_ID" \
      #       --project="$DEMO_GCP_ACCOUNT_ID" \
      #       --description="Copied from DEV on $(date)"