name: Web App CI
 
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Web App Tests
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USERNAME : ${{ secrets.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}  
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}  
        ports:
          - 3306:3306
        
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
    
 
    
 
      - name: Ensure Correct Authentication Method
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=$DB_PASSWORD -e
          "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '$DB_PASSWORD';
          FLUSH PRIVILEGES;"
 
      - name: Install Dependencies
        run: npm install
 
      - name: Run Tests
        run: npm test