name: Web App CI
 
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Web App Tests
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USERNAME : ${{ secrets.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify Database
        run: |
          echo "Checking if database exists..."
          mysql -h127.0.0.1 -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "
          SHOW DATABASES LIKE '${{ secrets.DB_DATABASE }}';
          "
 
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          SERVER_PORT: "8800"
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: "127.0.0.1"
          PORT: "3306"
